[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "wind-turbine-bem"
version = "0.1.0"
description = "A Python package for Wind Turbine BEM (Blade Element Momentum) Theory."
authors = ["Arianna, Beatrice, Giovanni"]
license = "MIT"
readme = "README.md"
packages = [{include = "wind_turbine_bem"}]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.21"
matplotlib = "^3.4"
pytest = "^6.2"
pytest-cov = "^2.12"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pylint = "^2.9"
coverage = "^5.5"

[tool.poetry.scripts]
main = "examples.main:main"